# Cloudflare Workers 配置文件
# 用于 OpenAI to Z.ai Proxy

name = "openai-to-zai-proxy"
main = "worker.js"
compatibility_date = "2024-01-01"

# 公开的环境变量（非敏感信息）
[vars]
ANON_TOKEN_ENABLED = "true"      # 是否启用匿名 token 获取
THINK_TAGS_MODE = "show"         # 思考内容处理: strip(不显示)/show(显示,使用reasoning_content字段)
DEBUG_MODE = "true"              # 调试模式（临时启用以排查卡顿问题）

# 敏感信息（secrets）需要通过命令行设置：
# wrangler secret put DOWNSTREAM_KEY
# wrangler secret put UPSTREAM_TOKEN
#
# DOWNSTREAM_KEY: 下游客户端的 API Key（必需）
# UPSTREAM_TOKEN: 上游 Z.ai 的固定 Token（可选，如果启用匿名token可留空）

# 开发环境配置（可选）
# [env.dev]
# vars = { DEBUG_MODE = "true" }

# 生产环境配置（可选）
# [env.production]
# vars = { DEBUG_MODE = "false" }
